version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-x
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: eywa
      POSTGRES_PASSWORD: easypassword 
      POSTGRES_DB: nexux
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data
